[phases.setup]
nixPkgs = ['nodejs_23', 'pnpm']

[phases.install]
cmds = ['rm -rf node_modules && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build']
cacheDirectories = ['node_modules/.cache', '.next/cache']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
NIXPACKS_PATH = "/app"